name: Build with lualatex (and publish to gh-pages)
on:
  push:
  pull_request:
  schedule:
    - cron: '1 2 2,16 * *'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
     - name: Compile main-english.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main-english.tex
          args:
